name:                necogda
version:             0.1.0.0
github:              "0xd34df00d/necogda"
license:             BSD3
author:              "Georg Rudoy"
maintainer:          "0xd34df00d@gmail.com"
copyright:           "2021 Georg Rudoy"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/0xd34df00d/necogda#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- bytestring-trie
- containers
- data-default
- extra
- hashable
- interpolate
- mtl
- nvim-hs >= 2.1.0.7
- text
- vector
- unordered-containers
- unliftio

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  necogda:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - necogda
  standalone:
    main:                Main.hs
    source-dirs:         standalone
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - necogda
  tablegen:
    main:                Main.hs
    source-dirs:         tablegen
    ghc-options:
    - -rtsopts
    dependencies:
    - megaparsec
    - sexpresso
    - uniplate

tests:
  necogda-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - necogda
