resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/18/12.yaml
packages:
- .
extra-deps:
- bytestring-trie-0.2.5.2
- nvim-hs-2.1.0.7
- sexpresso-1.2.1.0
